name: habit-partner

on:
  schedule: # Trigger every day
    - cron: '30 02 * * *'
  workflow_dispatch: # Run workflow manually

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run
      env:
        TODOIST_APIKEY: ${{ secrets.TODOIST_APIKEY }}
      run: |
        python main.py
